version: "3"

volumes:
  dynamodb_data:

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/tmp/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
